# This is a basic workflow to help you get started with Actions

name: My-First-Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code 
      run: echo "💡 The ${{ https://github.com/WEBDNik/First_website/commit/8a2c2e4bfcd64e5409187a595749616f274196d2 }} repository has been cloned to the runner."
